# Generated by Django 4.0 on 2021-12-24 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='BloogODS!', max_length=255),
        ),
    ]
